---
- hosts: dev
  become: True
  tasks:
    - name: Install python2 pip
      yum:
        name: python2-pip
        state: present
      vars:
        ansible_python_interpreter: /usr/bin/python2
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: hariapp
        image: "amashhour/hariapp:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
